version: '3.9'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DB_URL}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - GUNICORN_PORT=${GUNICORN_PORT}
    volumes:
      - static_volume:/home/app/web/static 
      - media_volume:/home/app/web/media 
    depends_on:
      - db 
    networks:
      - app-network 
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app-network
  
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx 
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web/static 
      - media_volume:/home/app/web/media 
    depends_on:
      - web 
    networks:
      - app-network
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
   driver: bridge