# Generated by Django 5.0.9 on 2024-11-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="address",
            field=models.TextField(null=True),
        ),
    ]
