FROM nginx:1.25-alpine

# Remove default Nginx configuration and copy static files
RUN rm /etc/nginx/conf.d/default.conf && \
    mkdir -p /home/app/web/staticfiles /home/app/web/media && \
    chown -R nginx:nginx /home/app/web 

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx 
CMD ["nginx", "-g", "daemon off;"]