CREATE TABLE serd_cat_pick(
    id INT,
    station VARCHAR(255),
    year INT,
    month INT,
    day INT,
    hour INT,
    minutes_p INT,
    p_arr_sec DOUBLE PRECISION, 
    p_polarity VARCHAR(10),
    p_onset VARCHAR(10),
    minutes_s INT,
    s_arr_sec DOUBLE PRECISION,
    s_polarity VARCHAR(10),
    s_onset VARCHAR(10),
    ts_tp DOUBLE PRECISION,
    minutes_origin INT,
    seconds_origin DOUBLE PRECISION,
    p_travel DOUBLE PRECISION,
    s_travel DOUBLE PRECISION,
    vp_vs DOUBLE PRECISION
);