# Generated by Django 5.2.3 on 2025-07-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='updates',
            table='project_updates',
        ),
    ]
