# Generated by Django 5.2.3 on 2025-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_updates_options_alter_updates_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='username',
            field=models.CharField(max_length=25, blank=True, null=True),
        ),
    ]