# Generated by Django 5.2.3 on 2025-07-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_hypocataloguplaod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HypoCatalogUplaod',
            new_name='Updates',
        ),
        migrations.AlterModelOptions(
            name='semlinitialcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semlpickingcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semlrelocatedcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='semlstation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serdinitialcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serdpickingcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serdrelocatedcatalog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serdstation',
            options={},
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
    ]
