# Generated by Django 5.2.3 on 2025-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_fix_updates_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='site_project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
