name: Deploy meq web app to DigitalOcean Droplet

on:
 push:
  branches:
    - main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   # checkout code
   - name: Checkout code
     uses: actions/checkout@v2

   # set up docker Buildx
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   # log in to Docker Hub
   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

   # build and push Djang app image
   - name: Build and push Django app
     uses: docker/build-push-action@v5
     with:
       context: .
       file: ./Dockerfile
       push: true
       tags: ${{ secrets.DOCKERHUB_USERNAME }}/meq-data-app:latest

   # Build and push Nginx image
   - name: Build and push Nginx
     uses: docker/build-push-action@v5
     with:
      context: .
      file: ./Dockerfile.nginx
      push: true 
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-nginx:latest

   # Deploy to DigitalOcean Droplet
   - name: Deploy to Droplet
     uses: appleboy/ssh-action@v1.0.3
     with:
      host: ${{ secrets.DO_HOST }}
      username: ${{ secrets.DO_USER }}
      key: ${{ secrets.DO_SSH_KEY }}
      script: |
       # log in to Docker Hub
       echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}"  --password-stdin

       # Create .env file with environment variables
       # Django Settings
       echo "DEBUG=False" >> .env
       echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
       echo "DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
       echo "DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8001" >> .env
       
       # Database Setting
       echo "DB_ENGINE=django.contrib.gis.db.backends.postgis" >> .env
       echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
       echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
       echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
       echo "DB_HOST=5432 >> .env
       echo "DATABASE_URL=${{ secrets.DB_URL }}" >> .env

       # Token
       echo "MAPBOX_API_TOKEN=${{ secrets.MAPBOX_API_TOKEN }}" >> .env

       # GDAL Library Path
       echo "GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so" >> .env

       # Gunicorn Variables
       echo "GUNICORN_WORKERS=3" >> .env
       echo "GUNICORN_PORT=8000" >> .env


       # copy docker-compose.yml to droplet
       cat << 'EOF' > docker-compose.yml
       version: '3.9'
       services:
        web:
         image: ${{ secrets.DOCKERHUB_USERNAME }}/my-data-app:latest
         env_file:
          - .env
         environment:
          - DATABASE_URL=${DATABASE_URL}
          - GUNICORN_WORKERS=${GUNICORN_WORKERS}
          - GUNICORN_PORT=${GUNICORN_PORT}
         volumes:
          - static_volume:/home/app/web/static
          - media_volume:/home/app/web/media
         depends_on:
          - db
         networks:
          - app-network
        db:
         image: postgis/postgis:16-3.4
         env_file:
          - .env
         ports:
          - "5432:5432"
         environment:
          - POSTGRES_USER=${{ secrets.DB_USERNAME }}
          - POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
          - POSTGRES_DB=${{ secrets.DB_NAME }}
         volumes:
          - postgres_data:/var/lib/postgresql/data
         networks: 
          - app-network
        nginx:
         image: ${{ secrets.DOCKERHUB_USERNAME }}/app-nginx:latest
         ports:
          - "8000:80"
         volumes:
          - static_volume:/home/app/web/static
          - media_volume:/home/app/web/media
         depends_on:
          - web
         networks:
          - app-network
       volumes:
        postgres_data:
        static_volume:
        media_volume:
       networks:
        app-network:
         driver: bridge
       
       EOF
       
       # Deploy with Docker Compose
       docker-compose --project-name meq-data-app down
       docker-compose --project-name meq-data-app up -d
   

