name: Deploy to DigitalOcean Droplet

on:
 push:
  branches:
    - main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   # checkout code
   - name: Checkout code
     uses: actions/checkout@v4

   # set up docker Buildx
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   # log in to Docker Hub
   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
       username: ${{secrets.DOCKERHUB_USERNAME}}
       password: ${{secrets.DOCKERHUB_TOKEN}}
   

